name: Nightly

on:
  pull_request:
    types: [labeled]
  schedule:
    - cron: '0 5 * * *'

jobs:
  industrial_ci:
    if: contains(github.event.pull_request.labels.*.name, 'check-tesseract-ros') || github.event.schedule == true
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [focal]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Free disk space
        continue-on-error: true
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        continue-on-error: true
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.distro }}/.ccache
          key: ${{ matrix.distro }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ matrix.distro }}-ccache-

      - name: Build workspace
        uses: 'marip8/industrial_ci@2f4c8ab919f0aafddd514e586325defabd2911ea'
        env:
          ADDITIONAL_DEBS: 'taskflow libompl-dev'
          ROS_DISTRO: false
          DOCKER_IMAGE: ghcr.io/tesseract-robotics/tesseract:${{ matrix.distro }}-master
          ROSDEP_SKIP_KEYS: "fcl opw_kinematics ros_industrial_cmake_boilerplate iwyu octomap catkin ompl taskflow descartes_light trajopt trajopt_ifopt trajopt_sco trajopt_sqp ruckig"
          CCACHE_DIR: ${{ github.workspace }}/${{ matrix.distro }}/.ccache
          BEFORE_INIT: './.github/workflows/add_sources.sh'
          AFTER_INIT: ''
          UPSTREAM_WORKSPACE: 'dependencies.repos'
          DOWNSTREAM_WORKSPACE: 'github:tesseract-robotics/tesseract_ros#master github:tesseract-robotics/tesseract_python#master'
          UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"
          TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"
          DOWNSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"
