name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 5 * * *'
  release:
    types:
      - released

jobs:
  ci:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [focal]
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      PUSH_DOCKER_IMAGE: ${{ github.ref == 'refs/heads/master' || github.event_name == 'release' }}
      TESSERACT_VERSION: 0.17
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Free disk space
        continue-on-error: true
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        continue-on-error: true
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.distro }}/.ccache
          key: ${{ matrix.distro }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ matrix.distro }}-ccache-

      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker meta-information
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=ref,event=branch,prefix=${{ matrix.distro }}-
            type=semver,pattern={{major}}.{{minor}},prefix=${{ matrix.distro }}-

      - name: Set build type
        run: |
          if [[ "${{ env.PUSH_DOCKER_IMAGE }}" = true ]]
          then
            echo "BUILD_TYPE=Release" >> $GITHUB_ENV
          else
            echo "BUILD_TYPE=Debug" >> $GITHUB_ENV
          fi

      - name: Build repository
        uses: 'marip8/industrial_ci@2f4c8ab919f0aafddd514e586325defabd2911ea'
        env:
          ADDITIONAL_DEBS: 'taskflow libompl-dev'
          ROS_DISTRO: false
          DOCKER_IMAGE: ${{ env.REGISTRY }}/tesseract-robotics/tesseract:${{ matrix.distro }}-${{ env.TESSERACT_VERSION }}
          UNDERLAY: /root/tesseract-robotics/tesseract_target_ws/install
          CCACHE_DIR: ${{ github.workspace }}/${{ matrix.distro }}/.ccache
          PREFIX: ${{ github.repository }}_
          BEFORE_INIT: './.github/workflows/add_sources.sh'
          AFTER_INIT: ''
          UPSTREAM_WORKSPACE: dependencies.repos
          UPSTREAM_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release"
          ROSDEP_SKIP_KEYS: "fcl opw_kinematics ros_industrial_cmake_boilerplate iwyu octomap catkin ompl taskflow descartes_light trajopt trajopt_ifopt trajopt_sco trajopt_sqp ruckig"
          TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DTESSERACT_ENABLE_TESTING=ON -DTESSERACT_WARNINGS_AS_ERRORS=OFF"
          DOCKER_COMMIT: ${{ steps.meta.outputs.tags }}

      - name: Push post-build Docker
        if: ${{ env.PUSH_DOCKER_IMAGE == 'true' }}
        run: docker push ${{ steps.meta.outputs.tags }}
